### ISSUE TITLE
session data gets modified before saving

### ISSUE THREAD

**Issue by longztian** [pavelvlasov/koa-generic-session-mongo#17]
[mongo store added two new fields (`sid` and `ttl`) to the session data](https://github.com/pavelvlasov/koa-generic-session-mongo/blob/master/src/store.js#L153) (in `set(sid, sess, ttl)`)

Issue found by user `yuu2lee4`:
> from: yuu2lee4
> and i found a strange thing,  i seted session.user, then i console it, the object has no 'sid' and 'ttl' , but after i setted session.pin ,  it has 'sid' and 'ttl'
> ![image](https://cloud.githubusercontent.com/assets/8046366/21292226/46d95d4c-c538-11e6-886d-c733c86b3f24.png)

**Comment by pavelvlasov** [comment]
thanks @longztian! fixed in https://github.com/pavelvlasov/koa-generic-session-mongo/commit/355eaa24ed3eec62aee4d21ec1e92ed3fba2ee5c
